### ISSUE TITLE
No Jellied Eels

### ISSUE THREAD

**Issue by Binh314** [eris6/odin-recipes#1]
I noticed that there are no recipes for jellied eels. Jellied eels are an important British delicacy. We need to add a jellied eels recipe ASAP. EOM.

Tasks:
- [x] Add jellied eels recipe.
- [x] Write an essay explaining the importance of jellied eels in British cuisine.
- [x] Worship the monarchy.

![image](https://github.com/user-attachments/assets/dd02e255-b116-45e4-8065-bd8a9ce95f09)

**Comment by eris6** [comment]
Added jellied eels recipe! Site should be up [here](https://eris6.github.io/odin-recipes/). I leave the essay writing about the importance of jellied eels in British cuisine and worshipping of the monarchy to you.

**Comment by Binh314** [comment]
@eris6 Missing two tasks. Please reopen.

**Comment by eris6** [comment]
I reopened it but I leave the two tasks as an exercise for the reader.
